import type { Metadata } from "next";
import "@/src/app/globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { Roboto_Mono } from "next/font/google";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const roboto = Roboto_Mono({
    subsets: ["latin"],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={roboto.className}>
                <div className="flex flex-col w-screen min-h-screen bg-gray-900 overflow-hidden">
                    <Header />
                    <main className="relative grow pb-14 shadow-md">
                        {children}
                    </main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
