import type { Metadata } from "next";
import "./globals.css";
import Container from "@/components/layout/container";
import Footer from "@/components/layout/footer";
import layout from "@/components/layout/layout";
import Layout from "@/components/layout/layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="ko"
            className="text-[4.666vw] break-keep bg-blue-50 sm:text-[2.666vw] lg:text-[1.333vw]"
        >
            <body>
                <Layout>
                    <>{children}</>
                </Layout>
            </body>
        </html>
    );
}
